(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/TabBar/TabBar"],{"02f0":function(e,t,a){"use strict";(function(e,a){Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var n={data:function(){return{TabBarList:[{index:0,name:"首页",img:"/static/tab_01.png",acImg:"/static/tab_02.png"},{index:1,name:"认养",img:"/static/tab_03.png",acImg:"/static/tab_04.png"},{index:4,name:"我的",img:"/static/tab_09.png",acImg:"/static/tab_10.png"}],codeheight:0,isOverall:0,phoneModel:""}},props:{tabBarShow:{type:Number,default:0}},mounted:function(){try{e.getSystemInfoSync();var t=this;e.getSystemInfo({success:function(e){console.log(e.brand),console.log(e.model),console.log(e.screenWidth),console.log(e.screenHeight),t.codeheight=Math.round(e.screenHeight),t.phoneModel=e.model,e.model.search("iPhone")?t.isOverall=0:Math.round(e.screenHeight)>740&&(t.isOverall=1),console.log(t.isOverall)}})}catch(a){}},methods:{onTabBar:function(e,t){switch(e.index){case 0:a.switchTab({url:"/pages/home/home"});break;case 1:a.switchTab({url:"/pages/ry/ry"});break;case 2:a.switchTab({url:"/pages/discover/discover"});break;case 3:a.switchTab({url:"/pages/cart/cart"});break;case 4:a.switchTab({url:"/pages/my/my"});break}}}};t.default=n}).call(this,a("df3c")["default"],a("3223")["default"])},"0839":function(e,t,a){},"1cfd":function(e,t,a){"use strict";a.r(t);var n=a("c5d4"),c=a("5074");for(var o in c)["default"].indexOf(o)<0&&function(e){a.d(t,e,(function(){return c[e]}))}(o);a("aa1d");var r=a("828b"),i=Object(r["a"])(c["default"],n["b"],n["c"],!1,null,"d5c13c3a",null,!1,n["a"],void 0);t["default"]=i.exports},5074:function(e,t,a){"use strict";a.r(t);var n=a("02f0"),c=a.n(n);for(var o in n)["default"].indexOf(o)<0&&function(e){a.d(t,e,(function(){return n[e]}))}(o);t["default"]=c.a},aa1d:function(e,t,a){"use strict";var n=a("0839"),c=a.n(n);c.a},c5d4:function(e,t,a){"use strict";a.d(t,"b",(function(){return n})),a.d(t,"c",(function(){return c})),a.d(t,"a",(function(){}));var n=function(){var e=this.$createElement;this._self._c},c=[]}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/TabBar/TabBar-create-component',
    {
        'components/TabBar/TabBar-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('df3c')['createComponent'](__webpack_require__("1cfd"))
        })
    },
    [['components/TabBar/TabBar-create-component']]
]);
